# Generated by Django 3.2.10 on 2021-12-13 19:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('product', django.db.models.manager.Manager()),
            ],
        ),
    ]
